### ISSUE TITLE
V0.3 feedback 

### ISSUE THREAD

**Issue by damithc** [CS2103AUG2016-W09-C1/main#45]
I'm giving you guys one day to do any further updates to the user guide and developer guide (_**if**_ you want to do any further updates based on what I said during the tutorial)  before I review them on GitHub.

**Comment by unusep** [comment]
Hey prof, thank you for your feedback. We will try to stick with our currently proposed GUI and downsize it if we cannot meet our target by V0.4.

**Comment by damithc** [comment]
My feedback below.

## Developer guide
- You seem to be following the given design closely and the diagram seem to be updated to match your code
- Suggested additions:
  - explain how you designed the 'undo' operation (there are multiple ways of doing it) 
  - how you represent different task types. It's not immediately clear from the class diagram.

## User Guide
- Update the UI sketch to match what you plan to deliver. If it's too much work to update all screenshots, update at least the main UI sketch given in the README.md 
- There's something wrong with the 'Foreward' section. Some parts don't make sense. 
  ![image](https://cloud.githubusercontent.com/assets/1673303/19547010/db373090-96c6-11e6-8fa4-940caf955176.png)

#### Command Summary
- This section will be used heavily by our testers, so make it easy to use.
- Supported date/time formats should be here too.
- Give examples of commands where possible.
